# Generated by Django 3.1.5 on 2021-01-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('school_address', models.CharField(default='https://canvas.instructure.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=1000)),
                ('course_code', models.CharField(max_length=10)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleCanvasAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=1000)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvascourse')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=1000)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('description', models.CharField(max_length=100000)),
                ('can_submit', models.BooleanField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvascourse')),
                ('simple_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignments.simplecanvasassignment')),
            ],
        ),
    ]
