# Generated by Django 3.1.5 on 2021-02-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('school_address', models.CharField(default='https://canvas.instructure.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_name', models.CharField(default='canvas', max_length=20)),
                ('assignment_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(null=True, verbose_name='due date')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CanvasCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_name', models.CharField(default='canvas', max_length=20)),
                ('course_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=10)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleClassroomCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_name', models.CharField(default='google_classroom', max_length=20)),
                ('course_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.googleclassroom')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleClassroomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_name', models.CharField(default='google_classroom', max_length=20)),
                ('assignment_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(null=True, verbose_name='due date')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.googleclassroomcourse')),
                ('lms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.googleclassroom')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasTextSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_name', models.CharField(default='canvas', max_length=20)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvasassignment')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvascourse')),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.canvas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasFileSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_name', models.CharField(default='canvas', max_length=20)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvasassignment')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvascourse')),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.canvas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='canvasassignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvascourse'),
        ),
        migrations.AddField(
            model_name='canvasassignment',
            name='lms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvas'),
        ),
    ]
