# Generated by Django 3.1.5 on 2021-01-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasassignment',
            name='lms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvas'),
        ),
        migrations.AddField(
            model_name='simplecanvasassignment',
            name='lms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.canvas'),
        ),
        migrations.AlterField(
            model_name='canvasassignment',
            name='assignment_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='canvasassignment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='canvasassignment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='canvascourse',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='canvascourse',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
