# Generated by Django 3.1.5 on 2021-01-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20210129_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasassignment',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='simplecanvasassignment',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='due date'),
        ),
    ]
