# Generated by Django 3.1.5 on 2021-01-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20210129_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasassignment',
            name='can_submit',
        ),
        migrations.RemoveField(
            model_name='canvasassignment',
            name='simple_assignment',
        ),
        migrations.AlterField(
            model_name='simplecanvasassignment',
            name='assignment_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='simplecanvasassignment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
