# Generated by Django 3.1.5 on 2021-02-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20210130_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleClasroomCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.googleclassroom')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleClasroomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(null=True, verbose_name='due date')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.googleclasroomcourse')),
                ('lms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.googleclassroom')),
            ],
        ),
    ]
