# Generated by Django 3.1.5 on 2021-02-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_googleclasroomassignment_googleclasroomcourse_googleclassroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleClasroomAssignment',
            new_name='GoogleClassroomAssignment',
        ),
        migrations.RenameModel(
            old_name='GoogleClasroomCourse',
            new_name='GoogleClassroomCourse',
        ),
    ]
